spring:
  profiles:
    active: develop
  thymeleaf:
    cache: false
    prefix: classpath:/templates
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
#        generate_statistics: true
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 10
      minimum-idle: 15
      pool-name: HikariConnectionPool

---
spring:
  profiles: production
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:h2:file:./bin/pims.db
    username: sa
    password:

---
spring:
  profiles: develop
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://localhost:5432/pimsdb
    username: pims_admin
    password: pimsAdmin

---
spring:
  profiles: test
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
