-- 初期値投入

-- ステータスマスタ
INSERT INTO STATUS_MASTER (STATUS_NAME, DISP_ORDER) VALUES ('新規', 0);
INSERT INTO STATUS_MASTER (STATUS_NAME, DISP_ORDER) VALUES ('進行中',	1);
INSERT INTO STATUS_MASTER (STATUS_NAME, DISP_ORDER) VALUES ('解決', 2);
INSERT INTO STATUS_MASTER (STATUS_NAME, DISP_ORDER) VALUES ('終了', 3);
INSERT INTO STATUS_MASTER (STATUS_NAME, DISP_ORDER) VALUES ('却下', 4);

-- 緊急度マスタ
INSERT INTO SEVERE_LEVEL_MASTER (SEVERE_LEVEL, DISP_ORDER) VALUES ('低', 0);
INSERT INTO SEVERE_LEVEL_MASTER (SEVERE_LEVEL, DISP_ORDER) VALUES ('中', 1);
INSERT INTO SEVERE_LEVEL_MASTER (SEVERE_LEVEL, DISP_ORDER) VALUES ('高', 2);
INSERT INTO SEVERE_LEVEL_MASTER (SEVERE_LEVEL, DISP_ORDER) VALUES ('非常に高', 3);

-- 工程マスタ
INSERT INTO PROCESS_MASTER (PROCESS_NAME, DISP_ORDER) VALUES ('基本設計', 0);
INSERT INTO PROCESS_MASTER (PROCESS_NAME, DISP_ORDER) VALUES ('詳細設計', 1);
INSERT INTO PROCESS_MASTER (PROCESS_NAME, DISP_ORDER) VALUES ('PG', 2);
INSERT INTO PROCESS_MASTER (PROCESS_NAME, DISP_ORDER) VALUES ('単体テスト', 3);
INSERT INTO PROCESS_MASTER (PROCESS_NAME, DISP_ORDER) VALUES ('結合テスト', 4);
INSERT INTO PROCESS_MASTER (PROCESS_NAME, DISP_ORDER) VALUES ('受入テスト', 5);

-- システム設定
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE) VALUES ('AppTitle', 'PIMS Beta');
