INSERT INTO CATEGORY_MASTER (CATEGORY_ID, CATEGORY_NAME, DISP_ORDER) VALUES ('1', 'Webアプリケーション', '0');
INSERT INTO CATEGORY_MASTER (CATEGORY_ID, CATEGORY_NAME, DISP_ORDER) VALUES ('2', 'Web API', '1');
INSERT INTO CATEGORY_MASTER (CATEGORY_ID, CATEGORY_NAME, DISP_ORDER) VALUES ('3', '端末用フロントエンド', '2');
INSERT INTO CATEGORY_MASTER (CATEGORY_ID, CATEGORY_NAME, DISP_ORDER) VALUES ('4', 'バッチ', '3');